name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ShellCheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ShellCheck
        run: shellcheck idmap-runc install test

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-24.04
    needs: lint
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Show environment
        run: |
          uname -r
          docker --version
          runc --version
          jq --version

      - name: Install idmap-runc
        run: sudo ./install

      - name: Run tests
        run: ./test
